name: mint-env

channels:
  - conda-forge

dependencies:
  - python>=3.10

# Setup dependencies.
  - setuptools
  - tbb-devel
  - numpy
  - pip

# Core dependencies.
  - libnetcdf
  - vtk>=9.1.0
  - xarray
  - defopt
  - python-mint>=1.25.0

